version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile
    networks:
      - custom-node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install && node src/index.js"
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - custom-node-network
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - custom-node-network
    ports:
      - "8080:80"

networks:
  custom-node-network:
    driver: bridge